export default {
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TODO",
  CHANGE_TODO_STATUS: "CHANGE_TODO_STATUS",
  CLEAR_COMPLETED_TODO: "CLEAR_COMPLETED_TODO",
  FILTERED_BY_ACTIVE: "FILTERED_BY_ACTIVE",
  FILTERED_BY_COMPLETED: "FILTERED_BY_COMPLETED",
  FILTERED_BY_ALL: "FILTERED_BY_ALL"
};
